notify:
  - platform: html5
    name: html5
    vapid_pub_key: !secret notify_html5_pub_key
    vapid_prv_key: !secret notify_html5_prv_key
    vapid_email: !secret notify_html5_email
  - name: all_users
    platform: group
    services:
    - service: mobile_app_iphone_qbr
  - name: user_qbr
    platform: group
    services:
    - service: mobile_app_iphone_qbr

