homeassistant:
  customize:
    switch.feliway:
      device_class: outlet
      icon: mdi:power-plug

input_boolean:
  feliway_periode:
    name: Période du Feliway

switch:
  - platform: template
    switches:
      feliway:
        friendly_name: Feliway
        value_template: "{{ is_state('switch.plug_osram_01', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.plug_osram_01
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.plug_osram_01

automation:
  - id: "feliway_on"
    alias: "Feliway : on"
    mode: restart
    trigger:
      - platform: time_pattern
        hours: "*"
        minutes: "0"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.feliway_periode
          state: "on"
        - condition: template
          value_template: >-
            {{ (now().hour % 2) == 0 }}
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.feliway
  - id: "feliway_off"
    alias: "Feliway : off"
    mode: restart
    trigger:
      - platform: time_pattern
        hours: "*"
        minutes: "0"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.feliway_periode
          state: "on"
        - condition: template
          value_template: >-
            {{ (now().hour % 2) == 1 }}
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.feliway
