input_datetime:
  wake_up_work_time:
    name: Heure
    icon: mdi:timer
    has_date: false
    has_time: true
  wake_up_occasional_time:
    name: Heure
    icon: mdi:timer
    has_date: true
    has_time: true

input_boolean:
  wake_up_work_state:
    name: Etat
    icon: mdi:alarm-check
  wake_up_work_light:
    name: En lumière
    icon: mdi:lightbulb-on-outline
  wake_up_work_music:
    name: En musique
    icon: mdi:music
  wake_up_work_go2sleep_alert:
    name: Avertissement dodo
    icon: mdi:bell-sleep
  wake_up_occasional_state:
    name: Etat
    icon: mdi:alarm-check
  wake_up_occasional_light:
    name: En lumière
    icon: mdi:lightbulb-on-outline
  wake_up_occasional_music:
    name: En musique
    icon: mdi:music
  wake_up_occasional_go2sleep_alert:
    name: Avertissement dodo
    icon: mdi:bell-sleep

input_select:
  wake_up_work_playlist:
    name: Playlist de réveil
    options:
      - Réveil de Quentin
      - Réveil Calme de Quentin
  wake_up_occasional_playlist:
    name: Playlist de réveil
    options:
      - Réveil de Quentin
      - Réveil Calme de Quentin

input_number:
  wake_up_work_light_time_transition:
    name: Durée de transition
    icon: mdi:transition-masked
    min: 0
    max: 60
    step: 5
    unit_of_measurement: minutes
  wake_up_work_light_shift_start_time:
    name: Décalage d'allumage
    icon: mdi:chart-gantt
    min: -30
    max: 30
    step: 5
    unit_of_measurement: minutes
  wake_up_work_go2sleep_time_before_alert:
    name: Avertir X heures avant le réveil
    icon: mdi:timer-sand
    min: 2
    max: 12
    step: 1
    unit_of_measurement: heures
  wake_up_work_light_max_brightness:
    name: Luminiosté maximale
    icon: mdi:brightness-percent
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "%"
  wake_up_work_music_max_volume:
    name: Volume maximal
    icon: mdi:volume-high
    min: 0
    max: 100
    step: 10
    unit_of_measurement: "%"
  wake_up_work_music_volume_transition:
    name: Durée de transition
    icon: mdi:transition
    min: 0
    max: 10
    step: 1
    unit_of_measurement: "minutes"
  wake_up_occasional_light_time_transition:
    name: Durée de transition
    icon: mdi:transition-masked
    min: 0
    max: 60
    step: 5
    unit_of_measurement: minutes
  wake_up_occasional_light_shift_start_time:
    name: Décalage d'allumage
    icon: mdi:chart-gantt
    min: -30
    max: 30
    step: 5
    unit_of_measurement: minutes
  wake_up_occasional_go2sleep_time_before_alert:
    name: Avertir X heures avant le réveil
    icon: mdi:timer-sand
    min: 2
    max: 12
    step: 1
    unit_of_measurement: heures
  wake_up_occasional_light_max_brightness:
    name: Luminiosté maximale
    icon: mdi:brightness-percent
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "%"
  wake_up_occasional_music_max_volume:
    name: Volume maximal
    icon: mdi:volume-high
    min: 0
    max: 100
    step: 10
    unit_of_measurement: "%"
  wake_up_occasional_music_volume_transition:
    name: Durée de transition
    icon: mdi:transition
    min: 0
    max: 10
    step: 1
    unit_of_measurement: "minutes"


automation:
  ###
  # Wake UP work
  ###
  ### Music
  - id: "wake_up_work_music"
    alias: "Wake UP work : start music"
    trigger:
      - platform: time
        at: input_datetime.wake_up_work_time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_music
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_state
          state: "on"
    action:
      - service: script.wake_up_music
        data:
          playlist: "{{ states('input_select.wake_up_work_playlist') }}"
          volume_transition: "{{ states('input_number.wake_up_work_music_max_volume') }}"
          volume_max: "{{ states('input_number.wake_up_work_music_volume_transition') }}"
  ### Light
  - id: "wake_up_work_light"
    alias: "Wake UP work : turn on light"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (((state_attr('input_datetime.wake_up_work_time', 'timestamp') | int) + ((states('input_number.wake_up_work_light_shift_start_time') | int) * 60)) | timestamp_custom('%H:%M', False)) }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_light
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_state
          state: "on"
    action:
      - service: script.wake_up_light
        data_template:
          time_transition: "{{ ((states('input_number.wake_up_work_light_time_transition') | int) * 60) }}"
          max_light_brightness: "{{ states('input_number.wake_up_work_light_max_brightness') }}"
  ### Go2Sleep Alert
  - id: wake_up_work_go2sleep_alert
    alias: "Wake UP work : send alert to go sleep"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (((state_attr('input_datetime.wake_up_work_time', 'timestamp') | int) - (states('input_number.wake_up_work_go2sleep_time_before_alert') | int * 3600)) | timestamp_custom('%H:%M', False)) }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_tomorrow
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_state
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_work_go2sleep_alert
          state: "on"
    action:
      - service: script.go2sleep_alert
        data:
          hours: "{{ (states('input_number.wake_up_work_go2sleep_time_before_alert') | int) }}"

  ###
  # Wake UP occasional
  ###
  ### Turn Off
  - id: "wake_up_occasional_turn_off"
    alias: "Wake UP Occasional : turn OFF"
    trigger:
      - platform: time
        at: input_datetime.wake_up_occasional_time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wake_up_occasional_state
          state: "on"
    action:
      - delay: 00:00:10
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.wake_up_occasional_state
  ### Music
  - id: "wake_up_occasional_music"
    alias: "Wake UP Occasional : start music"
    trigger:
      - platform: time
        at: input_datetime.wake_up_occasional_time
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wake_up_occasional_music
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_occasional_state
          state: "on"
    action:
      - service: script.wake_up_music
        data:
          playlist: "{{ states('input_select.wake_up_occasional_playlist') }}"
          volume_transition: "{{ states('input_number.wake_up_occasional_music_volume_transition') }}"
          volume_max: "{{ states('input_number.wake_up_occasional_music_max_volume') }}"
  ### Light
  - id: "wake_up_occasional_light"
    alias: "Wake UP Occasional : turn on light"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.date_time') == (((state_attr('input_datetime.wake_up_occasional_time', 'timestamp') | int) + ((states('input_number.wake_up_occasional_light_shift_start_time') | int) * 60)) | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wake_up_occasional_light
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_occasional_state
          state: "on"
    action:
      - service: script.wake_up_light
        data_template:
          time_transition: "{{ ((states('input_number.wake_up_occasional_light_time_transition') | int) * 60) }}"
          max_light_brightness: "{{ states('input_number.wake_up_occasional_light_max_brightness') }}"
  ### Go2Sleep Alert
  - id: wake_up_occasional_go2sleep_alert
    alias: "Wake UP occasional : send alert to go sleep"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.date_time') == (((state_attr('input_datetime.wake_up_occasional_time', 'timestamp') | int) - ((states('input_number.wake_up_occasional_go2sleep_time_before_alert') | int) * 3600 )) | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wake_up_occasional_state
          state: "on"
        - condition: state
          entity_id: input_boolean.wake_up_occasional_go2sleep_alert
          state: "on"
    action:
      - service: script.go2sleep_alert
        data:
          hours: "{{ (states('input_number.wake_up_occasional_go2sleep_time_before_alert') | int) }}"

script:
  wake_up_music:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify_quentin
          source: "Chambre"
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify_quentin
          media_content_type: music
          media_content_id: spotify:track:4jaXxB0DJ6X4PdjMK8XVfu
      - service: media_player.volume_set
        data:
          entity_id: media_player.spotify_quentin
          volume_level: 0.0
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify_quentin
          media_content_type: playlist
          media_content_id: >
            {% if playlist == 'Réveil Calme de Quentin' %}
              spotify:playlist:XXXX
            {% else %}
              spotify:playlist:XXXX
            {% endif %}
      - service: media_player.shuffle_set
        data:
          entity_id: media_player.spotify_quentin
          shuffle: true
      - service: media_player.media_pause
        target:
          entity_id: media_player.spotify_quentin
      - delay: 
          seconds: "2"
      - service: media_player.media_play
        target:
          entity_id: media_player.spotify_quentin
      - alias: "Volume transition"
        repeat:
          while:
            - condition: template
              value_template: "{{ ((state_attr('media_player.spotify_quentin', 'volume_level') * 100) | int) < (volume_max | int) }}"
          sequence:
            - service: media_player.volume_set
              target:
                entity_id: media_player.spotify_quentin
              data_template:
                volume_level: >-
                  {%- if volume_transition == 0 -%}
                  {{ (volume_max / 100) }}
                  {%- else -%}
                  {{ ((state_attr('media_player.spotify_quentin', 'volume_level') * 100 + 1) / 100) }}
                  {%- endif -%}
            - delay: 
                milliseconds: "{{ ((((volume_transition | int ) * 60  / (volume_max | int )) * 1000) | int) }}"

  wake_up_light:
    sequence:
      - service: light.turn_on
        data:
          brightness_pct: 1
          color_name: tan
        target:
          entity_id: light.chambre
      - delay: "00:00:01"
      - service: light.turn_on
        data:
          brightness_pct: "{{ max_light_brightness }}"
          color_name: tan
          transition: "{{ time_transition }}"
        target:
          entity_id: light.chambre
  go2sleep_alert:
    sequence:
    - service: notify.notify
      data_template:
        title: "Information"
        message: >-
          Le réveil sonnera dans {{hours}} heures. Il est temps d'aller vous coucher.
