sensor:
  - platform: template
    sensors:
      alexa_echo_device_last_called:
        friendly_name: alexa_echo_device_last_called
        value_template: >
          {{ expand('group.echo_devices') | selectattr('attributes.last_called','eq',true) | map(attribute='entity_id') | list | first }}
      alexa_echo_device_last_called_do_not_disturb_state:
        friendly_name: alexa_echo_device_last_called_do_not_disturb_state
        value_template: >
          {% set last_called = states('sensor.alexa_echo_device_last_called') | regex_replace('^media_player\.','') %}
          {{ states('switch.'+last_called+'_do_not_disturb_switch') }}
